TRANSLATION_EN_RU = {
    'id': 'Номер',
    'month': 'Месяц',
    'year': 'Год',
    'income': 'Доход',
    'outcome': 'Расход',
    'remainder': 'Остаток',
    'category': 'Категория',
    'spending': 'Расход',
    'revenue': 'Доход',
    'accumulation': 'Накопления',
    'Average': 'Среднее',
    'Accumulation': 'Накопления',
    'Spending': 'Траты',
    'Summary': 'Итог',
    'Income': 'Входящие',
    'Transfers': 'Переводы',
    'Eating out': 'Еда вне дома',
    'Groceries': 'Супермаркет',
    'Shopping': 'Покупки',
    'Transport': 'Транспорт',
    'Bills': 'Счета',
    'Entertainment': 'Развлечения',
    'General': 'Общие',
    'Finances': 'Финансы',
    'Holidays': 'Поездки',
    'Expenses': 'Затраты',
    'Charity': 'Благотворительность',
    'Personal care': 'Личная гигиена',
}

LANGUAGES = ['ru', 'en']
